### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by LarynQi**
Changes:
- a few
- fixed bug

### CODE REVIEW

**Comment by ochan1** [comment]
You, my good friend, are funny

**Comment by alexander-zw** [comment]
How much time did it take you to find every occurrence of HKN??

**Comment by ochan1** [comment]
Im sure this person just used Find and Replace

**Comment by alexander-zw** [comment]
> Im sure this person just used Find and Replace

But even the upper/lowercase is the same

**Pull request closed without merging**
