### PR TITLE
Markdown Security Patch

### PR DESCRIPTION
**Pull request by ochan1**

### CODE REVIEW

**Comment by ochan1** [comment]
The original bug from this branch:
https://github.com/compserv/hknweb/pull/266

Used patch from https://github.com/neutronX/django-markdownx/issues/163

**Comment by ochan1** [comment]
All "markdownify" function calls shall need to be called from the one made in "hknweb.utils" for security purposes

**Comment by ochan1** [comment]
There is no need to modify the backend data, but if any malicious HTML code is pushed, it will stay on the backend

However, before showing up to the end-user, the text is sanitized

**Review by sammaher1 — APPROVED** [review]
Looks good, tried to inject various alerts and images into event descriptions and urls, which all did not succeed. Markdownify being added as a dependency seems like a worthwhile trade for the security and access to markdown.

**Pull request merged**
