### PR TITLE
Python 3.7 on VM, Pip upgrade workaround, Upgrade some dependencies

### PR DESCRIPTION
**Pull request by ochan1**
For the pip upgrade workaround, see: https://github.com/hashicorp/vagrant/issues/12057

The long story short is that a Virtual Machine File System, VBFS, doesn't delete files fully and causes an environment error, and states that a folder during upgrades of pip is not empty

This is a workaround for use on the Virtual Machine only and overwrites files during the upgrade rather than deleting them first

Also on top of having the VirtualMachine to use Python 3.7 due to the end of life of Python 3.5 + some dependency upgrades

### CODE REVIEW

**Comment by bri25yu** [comment]
How should we go about testing that these changes don't break the website? e.g. re-deploying the website late at night and rolling back if something breaks

**Comment by ochan1** [comment]
For the Python 3.7 and Pip workaround, it's only the Vagrant local system

I can see this being a problem for the Dependencies in the requirements.txt

We can revert to an older copy if the website breaks or push a manually reverted requirements.txt worst comes to worse

**Comment by jameslzhu** [comment]
I would check what Python the OCF apphost is using and try to match their upgrade cadence, for dev/prod parity. Otherwise some newer Python features (f-strings, new methods, etc) might work in our VMs but break on prod.

**Comment by jameslzhu** [comment]
Oh, looks like you've already checked this and are pushing a virtualenv 3.7 in #113.

Maybe look into pyenv to build and install a 3.7 Python environment on the apphost as a user install. I don't think .venv is intended for multiple Python versions.

**Comment by ochan1** [comment]
OCF has Python 3.9, and Python 3.7 is only for Vagrant, so it's not too new compared to Python 3.9 so I'm assuming many dependencies should still support

**Comment by ochan1** [comment]
FYI I deleted my latest comment
(Gonna delete this one as well, just wanted to utilize the email feature)

**Comment by ochan1** [comment]
FYI I deleted my latest comment
Gonna delete this one as well

**Comment by ochan1** [comment]
> Clarification: the .venv on OCF uses Python 3.7 for some reason so this should work

Added in #311

**Comment by ochan1** [comment]
> Also, the fab file uses Python3.7 to make a venv at the start
> 
> https://github.com/compserv/hknweb/blob/master/fabfile.py#L145

Another one added in #311

**Pull request merged**
